const APPEARANCE_CONSTANTS = {
    SET_FONT_SIZE: "SET_FONT_SIZE",
    SET_COLORS: "SET_COLORS",
    SET_LINE_COLOR: "SET_LINE_COLOR",
    SET_DEFAULT_COLOR: "SET_DEFAULT_COLOR",
    SET_GREEN_COLOR: "SET_GREEN_COLOR",
    SET_RED_COLOR: "SET_RED_COLOR",
    SET_GRID_OPACITY: "SET_GRID_OPACITY",
    SET_DIMENSIONS: "SET_DIMENSIONS",
    // SET_RED_COLOR: "SET_RED_COLOR",
    SET_AUTO_SCROLL: "SET_AUTO_SCROLL",
    SET_IFRAME: "SET_IFRAME",
    SET_ACTIVE_TAB: "SET_ACTIVE_TAB",
    SET_ACTIVE_LANGUAGE: "SET_ACTIVE_LANGUAGE",
    SET_VISIBILITY_STATUS: "SET_VISIBILITY_STATUS",

}


export default APPEARANCE_CONSTANTS
