const AUTH_CONSTANTS = {
    TOGGLE_BG_SOUND: "TOGGLE_BG_SOUND",
    SET_AUTHENTICATION: "SET_AUTHENTICATION",
    SET_POSITION_DETAIL: "SET_POSITION_DETAIL",
    SET_BALANCE: "SET_BALANCE",
    SET_FIRST_INTERACT: "SET_FIRST_INTERACT",
    SET_USER: "SET_USER",
    SET_USER_WS: "SET_USER_WS",
    USER_LOGOUT: "USER_LOGOUT",
    SET_USER_USERNAME: "SET_USER_USERNAME",
    SET_AVATAR: "SET_AVATAR",
    SET_FAVORITES: "SET_FAVORITES",
    ADD_FAVORITES: "ADD_FAVORITES",
    REMOVE_FAVORITES: "REMOVE_FAVORITES",
    UPDATE_JACKPOT: "UPDATE_JACKPOT",
    CHECK_USER_ACTION: "CHECK_USER_ACTION",
}


export default AUTH_CONSTANTS
