const DATA_CONSTANTS = {
    SET_DATA: "SET_DATA",
    SET_LIMITS: "SET_LIMITS",
    APPEND_HISTORY_DATA: "APPEND_HISTORY_DATA",
    APPEND_DATA: "APPEND_DATA",
    SET_FAKE: "SET_FAKE",
    SET_FAKE1: "SET_FAKE1",
    SET_FAKE2: "SET_FAKE2",
    SET_FAKE3: "SET_FAKE3",
    SET_FAKE4: "SET_FAKE4",
    SET_INSTRUMENT_LIST: "SET_INSTRUMENT_LIST",
    SET_MARKET_TIMES: "SET_MARKET_TIMES",
    SET_REAL_OR_DEMO: "SET_REAL_OR_DEMO",
    SET_REAL_FIRST_WON: "SET_REAL_FIRST_WON",
}


export default DATA_CONSTANTS
