const INFORMATION_CONSTANTS = {
    SET_INSTRUMENTS: "SET_INSTRUMENTS",
    SET_CALCULATOR_SYMBOL: "SET_CALCULATOR_SYMBOL",
    SHOW_MY_BETS_ON_CHART: "SHOW_MY_BETS_ON_CHART",
    SET_ACTIVE_CHART: "SET_ACTIVE_CHART",
    SET_MODAL_TYPE: "SET_MODAL_TYPE",
    SET_BET_WAY: "SET_BET_WAY",
    SET_BETS_ABLE: "SET_BETS_ABLE",
    UPDATE_MY_BET: "UPDATE_MY_BET",
    REVISE_MY_BET: "REVISE_MY_BET",
    SHOW_SYMBOL_LIST: "SHOW_SYMBOL_LIST",
    SET_LAST_BAR: "SET_LAST_BAR",
    SET_MY_BETS: "SET_MY_BETS",
    BET_ON_CHART: "BET_ON_CHART",
    SET_POSITION_DETAIL: "SET_POSITION_DETAIL",
    SET_CHART_POSITION: "SET_CHART_POSITION",
    SET_NEW_BET: "SET_NEW_BET",
    SET_PUBLIC_BETS: "SET_PUBLIC_BETS",
    SET_PUBLIC_BETS_ALL: "SET_PUBLIC_BETS_ALL",
    SET_WHOLE_PUBLIC_BETS: "SET_WHOLE_PUBLIC_BETS",
    SET_WHOLE_ACTIVE_BETS: "SET_WHOLE_ACTIVE_BETS",
    RESULT_PUBLIC_BETS: "RESULT_PUBLIC_BETS",
    RESULT_BET: "RESULT_BET",
    SET_VISIBILITY_STATUS: "SET_VISIBILITY_STATUS",
    SET_RESOLUTION: "SET_RESOLUTION",
    SET_PARITY: "SET_PARITY",
    SET_LAST_DATA: "SET_LAST_DATA",
    SET_NOTIFICATIONS: "SET_NOTIFICATIONS",
    UPDATE_BET: "UPDATE_BET",

}


export default INFORMATION_CONSTANTS
